nodeLinker: node-modules

# essencial para desenvolvimento
enableScripts: true
enableInlineBuilds: true

# monorepo
enableTransparentWorkspaces: true

# Otimizações
compressionLevel: 0
enableTelemetry: false
